-- MySQL Database Schema and Seed Data for Pureplush
-- Database: kujannej_pureplush
-- --------------------------------------------------------

CREATE DATABASE IF NOT EXISTS `kujannej_pureplush` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `kujannej_pureplush`;

-- --------------------------------------------------------
-- Table structure for table `add_product`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `add_product`;
CREATE TABLE `add_product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `product_name` varchar(255) NOT NULL,
  `product_details` text DEFAULT NULL,
  `brief_details` text DEFAULT NULL,
  `product_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `original_price` decimal(10,2) NOT NULL DEFAULT 0.00,
  `product_category` varchar(100) DEFAULT NULL,
  `product_discount` int(11) DEFAULT 0,
  `image1` varchar(255) NOT NULL,
  `image2` varchar(255) DEFAULT NULL,
  `image3` varchar(255) DEFAULT NULL,
  `weight` varchar(50) DEFAULT NULL,
  `shelf_life` varchar(100) DEFAULT NULL,
  `point1` varchar(255) DEFAULT NULL,
  `point2` varchar(255) DEFAULT NULL,
  `point3` varchar(255) DEFAULT NULL,
  `point4` varchar(255) DEFAULT NULL,
  `point5` varchar(255) DEFAULT NULL,
  `productCode` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------
-- Dumping data for table `add_product`
-- --------------------------------------------------------

INSERT INTO `add_product` (
  `id`, 
  `product_name`, 
  `product_details`, 
  `brief_details`, 
  `product_price`, 
  `original_price`, 
  `product_category`, 
  `product_discount`, 
  `image1`, 
  `image2`, 
  `image3`, 
  `weight`, 
  `shelf_life`, 
  `point1`, 
  `point2`, 
  `point3`, 
  `point4`, 
  `point5`, 
  `productCode`
) VALUES
(
  26,
  'ABC Latte Mix(Malt) Powder',
  'Pureplush ABC Latte Mix Malt Powder – a wholesome blend of Apple, Beetroot, and Carrot with natural malt for a nourishing, tasty, and energizing health drink. 100g',
  'Pureplush ABC Latte Mix Malt Powder. Discover the goodness of nature in every sip with Apple, Beetroot, Carrot (ABC) and wholesome malt.',
  199.00,
  249.00,
  'ABC malt',
  20,
  'FaceWash/Herbal2.png',
  'FaceWash/Herbal1.png',
  'FaceWash/Herbal3.png',
  '100g',
  '12 Months',
  'Rich in Nutrients',
  'Immunity Support',
  'Glowing Skin & Eyes',
  NULL,
  NULL,
  'ABC-LMT-100'
),
(
  28,
  'Choco Multigrain Millet Malt Mix',
  'Pureplush Choco Multigrain Millet Malt Mix Powder – A delicious and nutritious blend of wholesome millets, grains, and natural cocoa, crafted to give you energy, strength, and taste in every sip. 100g.',
  'Pureplush Choco Multigrain Millet Malt Mix Powder is a perfect fusion of health and taste. Made with the goodness of nutrient-rich millets and natural cocoa.',
  199.00,
  249.00,
  'choco',
  20,
  'FaceWash/Herbal3.png',
  'FaceWash/Herbal2.png',
  'FaceWash/Herbal4.png',
  '100g',
  '12 Months',
  'Rich in Protein & Fiber',
  'No Preservatives',
  'Suitable for All Ages',
  NULL,
  NULL,
  'CHOCO-MMM-100'
),
(
  101,
  'Vedic Neem & Turmeric Soap',
  'Pureplush Handcrafted Neem & Turmeric soap combines natural skin protection with gentle botanical nourishment, leaving skin refreshed and pure. 100g.',
  'Vedic soap handcrafted with fresh neem extracts and wild turmeric root oil for daily antibacterial defense.',
  120.00,
  180.00,
  'Soaps',
  33,
  'Soap/Soap.png',
  'Soap/Soap2.jpg',
  'Soap/Soap3.jpg',
  '100g',
  '24 Months',
  '100% Handcrafted Soap',
  'Antibacterial Neem Extract',
  'Soothes Dry & Sensitive Skin',
  NULL,
  NULL,
  'SOAP-NEEM-100'
),
(
  102,
  'Honey & Sandalwood Glow Soap',
  'A moisturizing, glow-enhancing soap bar loaded with pure organic forest honey and steam-distilled sandalwood oils. 100g.',
  'Moisturizing bar containing deep forest honey and pure sandalwood to hydrate and restore natural radiance.',
  140.00,
  190.00,
  'Soaps',
  26,
  'Soap/Soap2.jpg',
  'Soap/Soap.png',
  'Soap/Soap3.jpg',
  '100g',
  '24 Months',
  'Forest Wild Honey',
  'Steam-Distilled Sandalwood',
  'Hydrates & Restores Glow',
  NULL,
  NULL,
  'SOAP-HNY-100'
),
(
  103,
  'Lavender Relaxation Soap',
  'Relax your mind and body with pure French lavender essential oils and cold-pressed botanical bases. 100g.',
  'A calming body wash bar infused with absolute lavender oil and skin-softening goat milk extracts.',
  130.00,
  180.00,
  'Soaps',
  27,
  'Soap/Soap3.jpg',
  'Soap/Soap.png',
  'Soap/Soap2.jpg',
  '100g',
  '24 Months',
  'French Lavender Oil',
  'Calming Aromatherapy Benefit',
  'Rich Conditioning Lather',
  NULL,
  NULL,
  'SOAP-LVD-100'
),
(
  104,
  'Rosemary & Tea Tree Shampoo Bar',
  'A luxurious solid shampoo bar formulated with fresh rosemary herbs and organic tea tree oils to reduce dandruff and strengthen hair roots. 80g.',
  'Solid zero-waste shampoo bar loaded with rosemary leaves and tea tree oil for clean scalp and healthy hair.',
  220.00,
  280.00,
  'Shampoo',
  21,
  'Shampoobar/Shampoobar.png',
  'Shampoobar/Shampoobar2.png',
  NULL,
  '80g',
  '18 Months',
  'Zero Waste Solid Bar',
  'Tea Tree Oil for Scalp Health',
  'Strengthens Root Follicles',
  NULL,
  NULL,
  'SHM-RMT-80'
),
(
  105,
  'Aloe Vera Rejuvenating Gel',
  'Pure fresh aloe vera inner leaf jelly to soothe, cool, and hydrate the face and body. 120g.',
  'Natural cooling moisturizer made with 99% pure aloe vera juice to soothe sunburn, acne, and redness.',
  180.00,
  240.00,
  'Others',
  25,
  '6330345451856531104.jpg',
  'FaceWash/Herbal4.png',
  'FaceWash/Herbal1.png',
  '120g',
  '24 Months',
  '99% Pure Inner Leaf Aloe',
  'Cools Sunburns & Skin Redness',
  'Non-Greasy Daily Hydration',
  NULL,
  NULL,
  'GEL-ALOE-120'
),
(
  106,
  'Kashmiri Saffron Glow Face Oil',
  'Traditional Kumkumadi tailam facial serum infused with authentic Kashmiri saffron threads, sandalwood, and licorice. 30ml.',
  'Premium night beauty serum made with Kashmiri saffron to improve skin texture and complexions.',
  399.00,
  499.00,
  'Moringa',
  20,
  'FaceWash/Herbal4.png',
  'FaceWash/Herbal2.png',
  'FaceWash/Herbal3.png',
  '30ml',
  '18 Months',
  'Authentic Kumkumadi Formulation',
  'Infused with Real Saffron Threads',
  'Fades Dark Spots & Pigmentation',
  NULL,
  NULL,
  'OIL-KSM-30'
),
(
  107,
  'Charcoal & Bamboo Shampoo Bar',
  'Pureplush Charcoal & Bamboo Shampoo Bar provides deep scalp detox, pulling out oils and toxins while moisturizing with organic coconut and argan base. 80g.',
  'Detoxifying solid shampoo bar with active bamboo charcoal and tea tree for clean, bouncy hair.',
  230.00,
  290.00,
  'Shampoo',
  21,
  'Shampoobar/Shampoobar2.png',
  'Shampoobar/Shampoobar.png',
  NULL,
  '80g',
  '18 Months',
  'Active Bamboo Charcoal',
  'Deep Scalp Detoxification',
  'Restores Volume & Shine',
  NULL,
  NULL,
  'SHM-CBC-80'
),
(
  108,
  'Vedic Neem & Aloe Facewash',
  'Gentle, non-drying foaming facewash packed with active neem leaves and cooling aloe vera gel to wash away impurities and fight acne-causing germs. 150ml.',
  'Organic purifying facewash formulated with neem leaf extracts and soothing aloe vera.',
  190.00,
  250.00,
  'Moringa',
  24,
  'FaceWash/Herbal1.png',
  'FaceWash/Herbal2.png',
  'FaceWash/Herbal3.png',
  '150ml',
  '24 Months',
  'Purifying Organic Neem',
  'Hydrating Aloe Vera Gel',
  'Fights Acne & Impurities',
  NULL,
  NULL,
  'FW-NMA-150'
);
